name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
# BU KISMI EKLE:
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Build Raylib for Web
        run: |
          git clone --depth 1 https://github.com/raysan5/raylib.git raylib_src
          cd raylib_src/src
          make PLATFORM=PLATFORM_WEB -e
          # Dikkat: Buradaki kaynak dosya ismini derleyicinin ürettiğiyle aynı yapıyoruz
          cp libraylib.a ../../libraylib_web.a || cp libraylib.web.a ../../libraylib_web.a
          cd ../..

      - name: Build Project with Emscripten
        run: |
          # Klasördeki eski libraylib.a yerine yeni derlenen libraylib_web.a kullanılıyor
          emcc main.cpp -o index.html \
            -I. -I./raylib_src/src \
            ./libraylib_web.a \
            -s USE_GLFW=3 -s WASM=1 -s ASYNCIFY \
            -s GL_ENABLE_GET_PROC_ADDRESS=1 \
            -s ALLOW_MEMORY_GROWTH=1 \
            --preload-file pota.png \
            -DPLATFORM_WEB

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
         
